service: landsat

provider:
  name: aws
  region: us-west-2
  runtime: python3.7
  stage: ${opt:stage, 'production'}
  deploymentBucket: ${opt:bucket}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::landsat-pds*"

  environment:
    VSI_CACHE: TRUE
    VSI_CACHE_SIZE: 536870912
    CPL_TMPDIR: /tmp
    CPL_VSIL_CURL_ALLOWED_EXTENSIONS: .tif,.TIF,.ovr
    GDAL_CACHEMAX: 512
    GDAL_DATA: /opt/share/gdal
    GDAL_DISABLE_READDIR_ON_OPEN: FALSE
    GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
    GDAL_HTTP_MULTIPLEX: YES
    GDAL_HTTP_VERSION: 2
    PROJ_LIB: /opt/share/proj
    PYTHONWARNINGS: ignore
    TOKEN: ${env:SECRET_TOKEN}
  
  apiGateway:
    binaryMediaTypes:
      - '*/*'
    minimumCompressionSize: 1

package:
  artifact: ../../package.zip

functions:
  tiler:
    layers:
      - arn:aws:lambda:${self:provider.region}:524387336408:layer:gdal24-py37-geo:2
    handler: remotepixel_tiler.landsat.APP
    memorySize: 1536
    timeout: 10
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true